# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Check Yarn PM

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["develop", "main"]

jobs:
  check_js_lockfile:
    runs-on: ubuntu-latest
    name: Check JS Lockfile
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Frontend Lockfile
        run: cd ram-front && sh -c "if [ -f yarn.lock -a ! -f package-lock.json ]; then exit 0; else echo 'yarn.lock is missing or package-lock.json exists'; exit 1; fi"
      - name: Check Backend Lockfile
        run: cd ram-back && sh -c "if [ -f yarn.lock -a ! -f package-lock.json ]; then exit 0; else echo 'yarn.lock is missing or package-lock.json exists'; exit 1; fi"
